### ISSUE TITLE
Failed to Verify jwt

### ISSUE THREAD

**Issue by bayboraoren** [griffio/spring-security-auth0-sample#1]
I don't know why ? call api is working nice, spring backend working nice but when code break point coming to Auth0AuthenticationProvider line:42 if (!jwt.verify(macClientSecret)) {   line verify not verified.

{"timestamp":1426860917007,"status":401,"error":"Unauthorized","message":"Authentication Failed: Failed to Verify jwt","path":"/authorised/handshake/"}

**Comment by griffio** [comment]
Thanks for raising this issue - I will look into shortly and get back to you soon.

**Comment by griffio** [comment]
It should work now - It looked like the ClientSecret needed to be base64Url decoded.

You can use http://jwt.io inspect any jwt tokens you may have.

Steps that you should perform in case of problems/questions - let me know
0. Configure index.js with your auth0 domain and clientid.
1. npm run bundle
2. ./gradlew bootRun -Pauth0="--auth0.clientId=FIXME,--auth0.clientSecret=FIXME"
3.http://localhost:8080/index.html
4.login with your auth0 user
5.click button for userInfo request via ajax
6.This will use the bearer token to call /authorised/handshake
7.Use bearer token from Curl etc

This project in my github may not be exactly what you are looking for, since it takes a simple pre-authenticate token. If you are just investigating approaches, depending on the kind of application you are trying, Auth0 have recently pushed a react version https://github.com/auth0/auth0-react.

Regards, griffio.

**Comment by bayboraoren** [comment]
Thank you
